version: '3.8'

services:
  hanappfe:
    build: .
    volumes:
      - ./node_modules:/app/node_modules
    networks:
      - hanapp_network
    ports:
      - "3000:3000"

networks:
  hanapp_network:
    name: hanapp_network
    external: true